
package com.mycompany.oopfinals;


import java.awt.*;
import java.sql.*;
import javax.swing.*;

public class DashboardPanel extends javax.swing.JPanel {

private SalesGraphPanel salesGraphPanel;
private JTextArea lowStockTextArea;
private Runnable createOrderAction;
private Runnable accountAction;

public void loadDashboard() {
    try {
        Connection conn = DBConnection.getConnection();

        PreparedStatement ps = conn.prepareStatement(
            "SELECT " +
            "COUNT(*) AS total_orders, " +
            "SUM(CASE WHEN TRIM(status)='Pending' THEN 1 ELSE 0 END) AS pending_orders, " +
            "SUM(CASE WHEN TRIM(status)='Processing' THEN 1 ELSE 0 END) AS processing_orders, " +
            "SUM(CASE WHEN TRIM(status)='Completed' THEN 1 ELSE 0 END) AS completed_orders " +
            "FROM orders"
        );

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            totalOrdersNumberLabel.setText(String.valueOf(rs.getInt("total_orders")));
            pendingOrdersNumberLabel.setText(String.valueOf(rs.getInt("pending_orders")));
            processingOrdersNumberLabel.setText(String.valueOf(rs.getInt("processing_orders")));
            completedOrdersNumberLabel.setText(String.valueOf(rs.getInt("completed_orders")));
        }

        PreparedStatement stockPs = conn.prepareStatement(
            "SELECT name, stock FROM products WHERE status='active' AND stock <= 5 ORDER BY stock ASC"
        );

        ResultSet stockRs = stockPs.executeQuery();

        StringBuilder lowStock = new StringBuilder();

        while (stockRs.next()) {
            lowStock.append(stockRs.getString("name"))
                    .append(" - only ")
                    .append(stockRs.getInt("stock"))
                    .append(" left\n");
        }

        if (lowStock.length() == 0) {
            lowStock.append("No low stock items.");
        }

        lowStockTextArea.setText(lowStock.toString());

        salesGraphPanel.loadGraphData();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load dashboard.");
    }
}

   public DashboardPanel(String username, Runnable createOrderAction, Runnable accountAction) {
    initComponents();

    this.createOrderAction = createOrderAction;
    this.accountAction = accountAction;

    accountNameButton.setText(username);

    salesGraphPanel = new SalesGraphPanel();

    graphContainerPanel.removeAll();
    graphContainerPanel.setLayout(new BorderLayout());
    graphContainerPanel.setPreferredSize(new Dimension(560, 330));
    graphContainerPanel.setMinimumSize(new Dimension(420, 300));
    graphContainerPanel.add(new JLabel("Sales Analysis"), BorderLayout.NORTH);
    graphContainerPanel.add(salesGraphPanel, BorderLayout.CENTER);

    lowStockTextArea = new JTextArea();
    lowStockTextArea.setEditable(false);
    lowStockTextArea.setFont(new Font("Poppins", Font.PLAIN, 12));

    graphContainerPanel1.removeAll();
    graphContainerPanel1.setLayout(new BorderLayout());
    graphContainerPanel1.setPreferredSize(new Dimension(280, 330));
    graphContainerPanel1.setMinimumSize(new Dimension(240, 300));
    graphContainerPanel1.add(new JLabel("Catalog Stock"), BorderLayout.NORTH);
    graphContainerPanel1.add(new JScrollPane(lowStockTextArea), BorderLayout.CENTER);

    loadDashboard();
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountNameButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalOrdersPanel = new javax.swing.JPanel();
        totalOrdersLabel = new javax.swing.JLabel();
        totalOrdersNumberLabel = new javax.swing.JLabel();
        pendingPanel = new javax.swing.JPanel();
        pendingLabel = new javax.swing.JLabel();
        pendingOrdersNumberLabel = new javax.swing.JLabel();
        processingPanel = new javax.swing.JPanel();
        processingLabel = new javax.swing.JLabel();
        processingOrdersNumberLabel = new javax.swing.JLabel();
        completedPanel = new javax.swing.JPanel();
        completedLabel = new javax.swing.JLabel();
        completedOrdersNumberLabel = new javax.swing.JLabel();
        completedLabel1 = new javax.swing.JLabel();
        dashboardCreateOrderButton = new javax.swing.JButton();
        graphContainerPanel = new javax.swing.JPanel();
        completedLabel2 = new javax.swing.JLabel();
        graphContainerPanel1 = new javax.swing.JPanel();
        completedLabel3 = new javax.swing.JLabel();

        accountNameButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        accountNameButton.setText("(name)");
        accountNameButton.setBorderPainted(false);
        accountNameButton.setContentAreaFilled(false);
        accountNameButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountNameButton.setMargin(new java.awt.Insets(2, 14, 3, 0));
        accountNameButton.addActionListener(this::accountNameButtonActionPerformed);

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setText("DASHBOARD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        totalOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalOrdersPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        totalOrdersLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalOrdersLabel.setText("Total Orders");

        totalOrdersNumberLabel.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        totalOrdersNumberLabel.setText("43");

        javax.swing.GroupLayout totalOrdersPanelLayout = new javax.swing.GroupLayout(totalOrdersPanel);
        totalOrdersPanel.setLayout(totalOrdersPanelLayout);
        totalOrdersPanelLayout.setHorizontalGroup(
            totalOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalOrdersPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(totalOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalOrdersPanelLayout.createSequentialGroup()
                        .addComponent(totalOrdersLabel)
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addComponent(totalOrdersNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalOrdersPanelLayout.setVerticalGroup(
            totalOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalOrdersPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(totalOrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalOrdersNumberLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pendingPanel.setBackground(new java.awt.Color(255, 255, 255));
        pendingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pendingLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        pendingLabel.setText("Pending");

        pendingOrdersNumberLabel.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        pendingOrdersNumberLabel.setText("3");

        javax.swing.GroupLayout pendingPanelLayout = new javax.swing.GroupLayout(pendingPanel);
        pendingPanel.setLayout(pendingPanelLayout);
        pendingPanelLayout.setHorizontalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendingPanelLayout.createSequentialGroup()
                        .addComponent(pendingLabel)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(pendingOrdersNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pendingPanelLayout.setVerticalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pendingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingOrdersNumberLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        processingPanel.setBackground(new java.awt.Color(255, 255, 255));
        processingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        processingLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        processingLabel.setText("Processing");

        processingOrdersNumberLabel.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        processingOrdersNumberLabel.setText("12");

        javax.swing.GroupLayout processingPanelLayout = new javax.swing.GroupLayout(processingPanel);
        processingPanel.setLayout(processingPanelLayout);
        processingPanelLayout.setHorizontalGroup(
            processingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processingPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(processingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processingPanelLayout.createSequentialGroup()
                        .addComponent(processingLabel)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(processingOrdersNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        processingPanelLayout.setVerticalGroup(
            processingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processingPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(processingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processingOrdersNumberLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        completedPanel.setBackground(new java.awt.Color(255, 255, 255));
        completedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        completedLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        completedLabel.setText("Completed");

        completedOrdersNumberLabel.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        completedOrdersNumberLabel.setText("30");

        javax.swing.GroupLayout completedPanelLayout = new javax.swing.GroupLayout(completedPanel);
        completedPanel.setLayout(completedPanelLayout);
        completedPanelLayout.setHorizontalGroup(
            completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(completedPanelLayout.createSequentialGroup()
                        .addComponent(completedLabel)
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(completedOrdersNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        completedPanelLayout.setVerticalGroup(
            completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(completedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completedOrdersNumberLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        completedLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        completedLabel1.setText("Orders");

        dashboardCreateOrderButton.setBackground(new java.awt.Color(27, 25, 24));
        dashboardCreateOrderButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dashboardCreateOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardCreateOrderButton.setText("+ Create Order ");
        dashboardCreateOrderButton.setBorderPainted(false);
        dashboardCreateOrderButton.setMaximumSize(new java.awt.Dimension(88, 29));
        dashboardCreateOrderButton.setMinimumSize(new java.awt.Dimension(88, 29));
        dashboardCreateOrderButton.setPreferredSize(new java.awt.Dimension(88, 29));
        dashboardCreateOrderButton.addActionListener(this::dashboardCreateOrderButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(completedLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dashboardCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalOrdersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completedLabel1)
                    .addComponent(dashboardCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalOrdersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        graphContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        completedLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        completedLabel2.setText("Sales Analysis");

        javax.swing.GroupLayout graphContainerPanelLayout = new javax.swing.GroupLayout(graphContainerPanel);
        graphContainerPanel.setLayout(graphContainerPanelLayout);
        graphContainerPanelLayout.setHorizontalGroup(
            graphContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphContainerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(completedLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graphContainerPanelLayout.setVerticalGroup(
            graphContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphContainerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(completedLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        graphContainerPanel1.setBackground(new java.awt.Color(255, 255, 255));
        graphContainerPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        completedLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        completedLabel3.setText("Catalog Stock");

        javax.swing.GroupLayout graphContainerPanel1Layout = new javax.swing.GroupLayout(graphContainerPanel1);
        graphContainerPanel1.setLayout(graphContainerPanel1Layout);
        graphContainerPanel1Layout.setHorizontalGroup(
            graphContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphContainerPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(completedLabel3)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        graphContainerPanel1Layout.setVerticalGroup(
            graphContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphContainerPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(completedLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(graphContainerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accountNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(accountNameButton))
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphContainerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNameButtonActionPerformed
 if (accountAction != null) {
        accountAction.run();
    }  
    }//GEN-LAST:event_accountNameButtonActionPerformed

    private void dashboardCreateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCreateOrderButtonActionPerformed

    if (createOrderAction != null) {
        createOrderAction.run();
    }
 
    }//GEN-LAST:event_dashboardCreateOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountNameButton;
    private javax.swing.JLabel completedLabel;
    private javax.swing.JLabel completedLabel1;
    private javax.swing.JLabel completedLabel2;
    private javax.swing.JLabel completedLabel3;
    private javax.swing.JLabel completedOrdersNumberLabel;
    private javax.swing.JPanel completedPanel;
    private javax.swing.JButton dashboardCreateOrderButton;
    private javax.swing.JPanel graphContainerPanel;
    private javax.swing.JPanel graphContainerPanel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pendingLabel;
    private javax.swing.JLabel pendingOrdersNumberLabel;
    private javax.swing.JPanel pendingPanel;
    private javax.swing.JLabel processingLabel;
    private javax.swing.JLabel processingOrdersNumberLabel;
    private javax.swing.JPanel processingPanel;
    private javax.swing.JLabel totalOrdersLabel;
    private javax.swing.JLabel totalOrdersLabel1;
    private javax.swing.JLabel totalOrdersLabel2;
    private javax.swing.JLabel totalOrdersLabel3;
    private javax.swing.JLabel totalOrdersLabel4;
    private javax.swing.JLabel totalOrdersLabel5;
    private javax.swing.JLabel totalOrdersLabel6;
    private javax.swing.JLabel totalOrdersNumberLabel;
    private javax.swing.JLabel totalOrdersNumberLabel1;
    private javax.swing.JLabel totalOrdersNumberLabel2;
    private javax.swing.JLabel totalOrdersNumberLabel3;
    private javax.swing.JLabel totalOrdersNumberLabel4;
    private javax.swing.JLabel totalOrdersNumberLabel5;
    private javax.swing.JLabel totalOrdersNumberLabel6;
    private javax.swing.JPanel totalOrdersPanel;
    private javax.swing.JPanel totalOrdersPanel1;
    private javax.swing.JPanel totalOrdersPanel2;
    private javax.swing.JPanel totalOrdersPanel3;
    private javax.swing.JPanel totalOrdersPanel4;
    private javax.swing.JPanel totalOrdersPanel5;
    private javax.swing.JPanel totalOrdersPanel6;
    // End of variables declaration//GEN-END:variables
}
